export const ONE_EMOJI = '1️⃣'
export const TWO_EMOJI = '2️⃣'
export const THREE_EMOJI = '3️⃣'
export const FOUR_EMOJI = '4️⃣'
export const FIVE_EMOJI = '5️⃣'
export const RED_EMOJI = '🟥'
export const BLACK_EMOJI = '⬛'
